[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "dcit316-hackathon-starter"
version = "0.0.1"
requires-python = ">=3.10"

[tool.setuptools]
packages = ["project"]