name: CI
on: [push, pull_request]

jobs:
  test-train-eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .              # <— install your package

      - name: Unit tests
        run: pytest -q                  # no PYTHONPATH hacks needed

      - name: Train baseline
        run: python -m project.train --task sentiment --lang twi --data_dir data/public_dev --out_dir models

      - name: Evaluate
        run: python -m project.eval --task sentiment --lang twi --data_dir data/public_dev --model_dir models --out reports/metrics.json

      - name: Grade
        run: python .classroom/grade.py reports/metrics.json
